# Generated by Django 2.2.3 on 2019-07-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='Наименование продукта')),
                ('description', models.TextField(verbose_name='Характеристики')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('created_ad', models.DateField(auto_now_add=True, verbose_name='Дата добавления:')),
                ('updated_ad', models.DateField(auto_now_add=True, verbose_name='Дата обновления:')),
                ('artikul', models.CharField(max_length=100, verbose_name='Код товара')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='media/products/', verbose_name='Фото товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.Category', verbose_name='Категория')),
            ],
        ),
    ]
